apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-request-no-limit-1
  labels:
    app: no-request-no-limit-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-request-no-limit-1
  template:
    metadata:
      labels:
        app: no-request-no-limit-1
    spec:
      containers:
      - name: no-request-no-limit-1
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          cat /dev/zero > /dev/null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-request-no-limit-2
  labels:
    app: no-request-no-limit-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-request-no-limit-2
  template:
    metadata:
      labels:
        app: no-request-no-limit-2
    spec:
      containers:
      - name: no-request-no-limit-2
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          cat /dev/zero > /dev/null
