apiVersion: apps/v1
kind: Deployment
metadata:
  name: 750-request-no-limit-1
  labels:
    app: 750-request-no-limit-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 750-request-no-limit-1
  template:
    metadata:
      labels:
        app: 750-request-no-limit-1
    spec:
      containers:
      - name: 750-request-no-limit-1
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          cat /dev/zero > /dev/null
        resources:
          requests:
            cpu: "750m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 100-request-100-limit-2
  labels:
    app: 100-request-100-limit-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 100-request-100-limit-2
  template:
    metadata:
      labels:
        app: 100-request-100-limit-2
    spec:
      containers:
      - name: 100-request-100-limit-2
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          cat /dev/zero > /dev/null
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
